// <auto-generated />
namespace Q4.Angular.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-21010")]
    public sealed partial class AddTasks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTasks));
        
        string IMigrationMetadata.Id
        {
            get { return "201311120949362_Add-Tasks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
